### ISSUE TITLE
HELP & How Get List Of cmds ?

### ISSUE THREAD

**Issue by EsmailELBoBDev2** [jagrosh/Selfbot#30]
[00:20:44] [Fatal] [RestAction]: RestAction queue returned failure: [ErrorResponseException] 0: Discord encountered an internal server error! Not good!
[00:20:44] [Fatal] [JDARequester]: Encountered an exception:
[00:20:44] [Fatal] [JDARequester]: com.mashape.unirest.http.exceptions.UnirestException: java.net.SocketException: Connection reset
        at com.mashape.unirest.http.HttpClientHelper.request(HttpClientHelper.java:143)
        at com.mashape.unirest.request.BaseRequest.asString(BaseRequest.java:56)
        at net.dv8tion.jda.core.requests.Requester.execute(Requester.java:132)
        at net.dv8tion.jda.core.requests.ratelimit.ClientRateLimiter$Bucket.run(ClientRateLimiter.java:202)
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.net.SocketException: Connection reset
        at java.net.SocketInputStream.read(Unknown Source)
        at java.net.SocketInputStream.read(Unknown Source)
        at sun.security.ssl.InputRecord.readFully(Unknown Source)
        at sun.security.ssl.InputRecord.read(Unknown Source)
        at sun.security.ssl.SSLSocketImpl.readRecord(Unknown Source)
        at sun.security.ssl.SSLSocketImpl.readDataRecord(Unknown Source)
        at sun.security.ssl.AppInputStream.read(Unknown Source)
        at org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:139)
        at org.apache.http.impl.io.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:155)
        at org.apache.http.impl.io.SessionInputBufferImpl.readLine(SessionInputBufferImpl.java:284)
        at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:140)
        at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:57)
        at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:261)
        at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:165)
        at org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:167)
        at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:272)
        at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:124)
        at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:271)
        at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
        at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
        at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
        at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:107)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:55)
        at com.mashape.unirest.http.HttpClientHelper.request(HttpClientHelper.java:138)
        ... 10 more

**Comment by jagrosh** [comment]
Have you tried restarting the entire bot (and then using the designated help command that it shows you once its fully loaded)?

**Comment by EsmailELBoBDev2** [comment]
yup & still not work :(

**Comment by jagrosh** [comment]
Are you using the most recent version?

**Comment by EsmailELBoBDev2** [comment]
yup

**Comment by jagrosh** [comment]
Do you consistently get this error every time you start? What is your internet speed? What large Discord servers is your account connected to? How much RAM does your computer have?

**Comment by EsmailELBoBDev2** [comment]
1-yes
2-1mb but real is 64kb/s
3-idk what mean
4-4gb

**Comment by jagrosh** [comment]
What are you running this on? The error (`java.net.SocketException: Connection reset`) implies that either the connection is not stable enough for a connection to Discord, or one (or both) sides are blocking the connection.
