### ISSUE TITLE
Error message when starting

### ISSUE THREAD

**Issue by tandpfun** [jagrosh/Selfbot#76]
I downloaded the files, and I tried to rune the .command file, but it said "Permission Denied." I ran all the commands in the file manually, but it couldn't open the jar file. I then ran the java command with the directory of the file and got this error;
`Exception in thread "main" java.lang.UnsupportedClassVersionError: jselfbot/JSelfBot : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
	at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
ThijsComputer:~ Thijs$ /Users/thijspieke/Desktop/Selfbot-master/src/`

**Comment by jagrosh** [comment]
Do you have JDK 1.8 installed (check with `java -version`)

**Comment by tandpfun** [comment]
java version "1.6.0_65"
Java(TM) SE Runtime Environment (build 1.6.0_65-b14-468)
Java HotSpot(TM) 64-Bit Server VM (build 20.65-b04-468, mixed mode)


nope. How do you get it?

**Comment by tandpfun** [comment]
I figured it out, but I still got the same error.

**Comment by tandpfun** [comment]
`Exception in thread "main" java.lang.UnsupportedClassVersionError: jselfbot/JSelfBot : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
	at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)`

**Comment by spotlightishere** [comment]
Double check that `java -version` says version 1.8.0 or similar - if it doesn't, you're probably still using JDK 1.6.0. If you don't have any program using 1.6, you can probably uninstall that version.

**Comment by tandpfun** [comment]
i checked the version again, and it is old. IDK why it didn't update. I got it from the java.com website

**Comment by tandpfun** [comment]
how do u uninstall it?

**Comment by spotlightishere** [comment]
Read https://java.com/en/download/help/uninstall_java.xml for some more information on that.

**Comment by tandpfun** [comment]
I can't sudo, is there any other way?

**Comment by spotlightishere** [comment]
Ah, are you using something Linux? You'd want to use your package manager (i.e `yum`, `apt`) to uninstall Java from there.

It's probably best to search how to install JDK 1.8, for example in Ubuntu you may want to use webupd8team's PPA (see http://www.webupd8.org/2012/09/install-oracle-java-8-in-ubuntu-via-ppa.html for more information).

Without sudo, it's much harder to install and use. You may want to ask whoever manages the system to install that for you.
